# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 22:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolioitem_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('html', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'ordering': ['order'],
                'verbose_name_plural': 'Privacy Policies',
                'abstract': False,
            },
        ),
    ]
